name: texBuild

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install texlive-base texlive-lang-german texlive-latex-extra texlive-bibtex-extra biber texlive-fonts-recommended

      - name: Build Latex
        run: |
          cd $GITHUB_WORKSPACE
          sudo pdflatex -file-line-error -interaction=nonstopmode -halt-on-error -output-format=pdf  $GITHUB_WORKSPACE/main.tex
          sudo biber --input-directory=$GITHUB_WORKSPACE --input-directory=./ main
          sudo pdflatex -file-line-error -interaction=nonstopmode -halt-on-error -output-format=pdf  $GITHUB_WORKSPACE/main.tex

      - name: Check built file
        run: sudo ls -la main.pdf

      - name: upload latest Build
        id: upload-release-asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: 'https://uploads.github.com/repos/Lukas-Heiligenbrunner/LatexActionTest/releases/assets/latest-build'
            asset_path: ./main.pdf
            asset_name: Diplomarbeit.pdf
            asset_content_type: application/pdf