name: Publish Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install texlive-base texlive-lang-german texlive-latex-extra texlive-bibtex-extra biber texlive-fonts-recommended

      - name: Build Latex
        run: |
          sudo pdflatex -file-line-error -interaction=nonstopmode -halt-on-error -output-format=pdf  $GITHUB_WORKSPACE/main.tex
          sudo biber --input-directory=$GITHUB_WORKSPACE --input-directory=./ main
          sudo pdflatex -file-line-error -interaction=nonstopmode -halt-on-error -output-format=pdf  $GITHUB_WORKSPACE/main.tex
          sudo pdflatex -file-line-error -interaction=nonstopmode -halt-on-error -output-format=pdf  $GITHUB_WORKSPACE/main.tex

      - name: Check built file
        run: sudo ls -la main.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Diplomarbeit ${{ github.ref }}
          body: Bildkorrektur für Oberflächeninspektion
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: Lukas-Heiligenbrujner/upload-release-asset@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./main.pdf
          asset_name: Diplomarbeit.pdf
          asset_content_type: application/pdf